apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-app-v1
  labels:
    app: 2048-app-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 2048-app-v1
  template:
    metadata:
      labels:
        app: 2048-app-v1
    spec:
      containers:
      - name: 2048-app-v1
        image: noscopev6/2048app
        ports:
        - containerPort: 80
